### ISSUE TITLE
Bug in public registration list

### ISSUE THREAD

**Issue by puiterwijk** [puiterwijk/regcfp#80]
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: Unhandled rejection TypeError: Cannot read property 'name' of null
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at null.<anonymous> (/srv/regcfp/routes/registration.js:84:42)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at tryCatcher (/srv/regcfp/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at Promise._settlePromiseFromHandler (/srv/regcfp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at Promise._settlePromiseAt (/srv/regcfp/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at Async._drainQueue (/srv/regcfp/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at Async._drainQueues (/srv/regcfp/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at Async.drainQueues (/srv/regcfp/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
Apr 08 21:26:35 regcfp.novalocal regcfp[1055]: at process._tickCallback (node.js:448:13)

**Comment by puiterwijk** [comment]
This was a data inconsistency.
